server:
  port: 7180

spring:
  application:
    name: aossia-cc-resource-server
  datasource:
    url: jdbc:mysql://localhost:3306/aossia_appspace_cc
    username: ccdbadmin
    password: P@ssp0rt
    driver-class-name: com.mysql.jdbc.Driver
    continueOnError: true
    testOnBorrow: true
    validationQuery: SELECT 1
    initialize: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.MySQL5Dialect
        archive:
          autodetection: class
        id:
          new_generator_mappings: true
        cache:
          use_second_level_cache: false
        show_sql: true
        format_sql: false
  mail:
    host: test
    username: test@aossia.com
    password:
    default-encoding: UTF-8

  oauth2:
    resource:
      jwt:
        keyValue: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB\n-----END PUBLIC KEY-----

cc:
  interval: 7200000
  intervalStrict: true
  unsecuredEndpoints: [ {ip: 127.0.0.1}, {ip: 10.3.7.58}, {ip: 10.1.7.9} ]
  mailProperties:
    adminMail: system-cc@aossia.com
  abandoned:
    - dimitar.dimitrov@aossia.com
    - mariana.ivanova@cityclinic.bg

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

